import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Ready from '@/components/Ready'
import AdminSideBar from '@/components/admin/AdminSideBar'
import { getSession } from 'next-auth/react'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AdminSideBar />
            <main className={styles.main}>
                <Header />
                <div id="container">
                    <Ready />
                </div>
            </main>
        </>
    )
}

export async function getServerSideProps(context: any) {
    const session = await getSession(context)

    if (!session)
        return {
            redirect: {
                permanent: false,
                destination: `/user/login`,
            },
            props: {},
        }
    else if (session.user.asLev < 5)
        return {
            redirect: {
                permanent: false,
                destination: '/',
            },
            props: {},
        }

    return {
        props: {},
    }
}
